project_id = "pavibobervhqkfzwkotw"

[functions.send-email]
verify_jwt = false

[functions.process-refund]
verify_jwt = false

[functions.invite-admin]
verify_jwt = false

[functions.accept-admin-invite]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.upload-psw-document]
verify_jwt = false

[functions.register-psw]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.mass-email-psws]
verify_jwt = false
