project_id = "pavibobervhqkfzwkotw"

[functions.send-email]
verify_jwt = false

[functions.process-refund]
verify_jwt = false

[functions.invite-admin]
verify_jwt = false

[functions.accept-admin-invite]
verify_jwt = false

[functions.process-notification-queue]
verify_jwt = false

[functions.geocode-postal-codes]
verify_jwt = false

[functions.upload-psw-document]
verify_jwt = false
